import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { requireAuth } from "@/lib/auth-guard";
import { generateMaintenanceSchedule } from "@/lib/maintenance/schedule-generator";
import type { MaintenanceCategory } from "@prisma/client";

export async function POST(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { error, session } = await requireAuth();
  if (error) return error;
  const { id } = await params;

  const tank = await prisma.tank.findFirst({
    where: { id, userId: session!.user.id },
    include: { plants: true },
  });
  if (!tank) return NextResponse.json({ error: "Not found" }, { status: 404 });

  // Remove existing auto-generated tasks for this tank
  await prisma.maintenanceTask.deleteMany({
    where: { tankId: id, isAutoGenerated: true },
  });

  const generated = generateMaintenanceSchedule(tank);
  const now = new Date();

  const tasks = await Promise.all(
    generated.map((t) =>
      prisma.maintenanceTask.create({
        data: {
          userId: session!.user.id,
          tankId: id,
          title: t.title,
          description: t.description,
          category: t.category as MaintenanceCategory,
          frequencyDays: t.frequencyDays,
          nextDue: new Date(now.getTime() + t.frequencyDays * 24 * 60 * 60 * 1000),
          isAutoGenerated: true,
        },
      })
    )
  );

  return NextResponse.json({ tasks, count: tasks.length });
}
